### ISSUE TITLE
String Concatenation fails (invalid Jump Dest / Memory out of bounds) 

### ISSUE THREAD

**Issue by rlaveycal** [eris-ltd/eris-db.js#27]
I'm trying to use the strConcat function from [here](https://github.com/oraclize/ethereum-api/blob/master/oraclizeAPI.sol#L189) but get errors when it is invoked. I've narrowed the problem down to the allocation of a string of a fixed size.

 This solidity function illustrates the problem

```
function getString2() constant returns (string){
    string memory abcde = new string(3);
    return "a";
}
```
When called from a node app

```	
contract.getString2(function(error, result){
    if (error) { throw error; }
    console.log("getString2 is:\t\t\t", result);
})
```
 
I get the following error 
```
[JSON RPC 2.0 Error] Message Id: 4, (INTERNAL_ERROR) - Memory out of bounds
Error callback from sendTransaction
/home/vagrant/.eris/apps/types/app.js:36
    if (error) { throw error; }
                 ^
 
Error: Memory out of bounds
    at /home/vagrant/.eris/apps/types/node_modules/eris-db/lib/rpc/http.js:79:22
    at httpRequest.onreadystatechange (/home/vagrant/.eris/apps/types/node_modules/eris-db/lib/rpc/http.js:103:17)
    at dispatchEvent (/home/vagrant/.eris/apps/types/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)
    at setState (/home/vagrant/.eris/apps/types/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:14)
    at IncomingMessage.<anonymous> (/home/vagrant/.eris/apps/types/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:431:13)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
```

Is this a compiler error (I'm using the default package manager compiler) or an EVM error?
- Eris 0.11.2
- Ubuntu 14.04

**Comment by NodeGuy** [comment]
This looks like an Eris DB error.  Ethan?

**Comment by somak12** [comment]
any update on this? I am stuck in a similar kind of error while trying to return array of elements.

**Comment by NodeGuy** [comment]
This is an Eris DB issue now being tracked here: https://github.com/eris-ltd/eris-db/issues/300
