### ISSUE TITLE
Incorrect private key crashes unsafe.js

### ISSUE THREAD

**Issue by slowtokyo** [eris-ltd/eris-db.js#29]
I was hacking around and got the following error that crashed my app when I intentionally put in a wrong private key. In `unsafe.js` there is a check to see if the private key length is correct, but there is no elegant check to see whether the private key is correct or not, so it crashes. When you can't broadcast a transaction becasue private key is incorrect, I think a simple error like "private key incorrect" is needed.
```
I have caught your message: [JSON RPC 2.0 Error] Message Id: 1, (INTERNAL_ERROR) - Error broadcasting transaction: Error invalid address
/Users/MacBookAir/.eris/apps/ohalo/node_modules/eris-contracts/node_modules/eris-db/lib/unsafe.js:116
        data2 = data2[1];
                     ^

TypeError: Cannot read property '1' of undefined
    at fixedCallback (/Users/MacBookAir/.eris/apps/ohalo/node_modules/eris-contracts/node_modules/eris-db/lib/unsafe.js:116:22)
    at /Users/MacBookAir/.eris/apps/ohalo/node_modules/eris-contracts/node_modules/eris-db/lib/rpc/http.js:79:13
    at httpRequest.onreadystatechange (/Users/MacBookAir/.eris/apps/ohalo/node_modules/eris-contracts/node_modules/eris-db/lib/rpc/http.js:103:17)
    at dispatchEvent (/Users/MacBookAir/.eris/apps/ohalo/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)
    at setState (/Users/MacBookAir/.eris/apps/ohalo/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:14)
    at IncomingMessage.<anonymous> (/Users/MacBookAir/.eris/apps/ohalo/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:431:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
```

**Comment by NodeGuy** [comment]
Thank you for the report.  I'm in the process of removing private keys from the JavaScript libraries entirely (https://github.com/eris-ltd/eris-contracts.js/issues/23) at which point this issue will be resolved.
